Traceback (most recent call last):
  File "/home/aim/anaconda3/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/aim/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aim/anaconda3/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aim/anaconda3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/aim/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/aim/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/aim/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
text = "Never give"
input_ids = tokenizer.encode(text, return_tensors='pt').to(device)
num_tokens_to_generate = 2
beam_width = 2

# Run Greedy Search
graph_greedy = nx.balanced_tree(1, num_tokens_to_generate, create_using=nx.DiGraph())
for node in graph_greedy.nodes:
    graph_greedy.nodes[node].update({
        'sequencescore': 0,
        'token': text
    })

graph = graph_greedy
greedy_output = greedy_search(input_ids, 0, num_tokens_to_generate)
plot_search_tree(graph_greedy, num_tokens_to_generate, 1, "Greedy Search")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [0;32m~/anaconda3/envs/book_env/lib/python3.10/site-packages/networkx/drawing/nx_agraph.py:301[0m, in [0;36mpygraphviz_layout[0;34m(G, prog, root, args)[0m
[1;32m    300[0m [38;5;28;01mtry[39;00m:
[0;32m--> 301[0m     [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mpygraphviz[39;00m
[1;32m    302[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m [38;5;28;01mas[39;00m err:

[0;31mModuleNotFoundError[0m: No module named 'pygraphviz'

The above exception was the direct cause of the following exception:

[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[8], line 16[0m
[1;32m     14[0m graph [38;5;241m=[39m graph_greedy
[1;32m     15[0m greedy_output [38;5;241m=[39m greedy_search(input_ids, [38;5;241m0[39m, num_tokens_to_generate)
[0;32m---> 16[0m [43mplot_search_tree[49m[43m([49m[43mgraph_greedy[49m[43m,[49m[43m [49m[43mnum_tokens_to_generate[49m[43m,[49m[43m [49m[38;5;241;43m1[39;49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mGreedy Search[39;49m[38;5;124;43m"[39;49m[43m)[49m

Cell [0;32mIn[4], line 7[0m, in [0;36mplot_search_tree[0;34m(graph, num_tokens_to_generate, beam_width, title)[0m
[1;32m      2[0m [38;5;250m[39m[38;5;124;03m"""Visualize search results as a tree."""[39;00m
[1;32m      3[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots(figsize[38;5;241m=[39m([38;5;241m3[39m [38;5;241m+[39m [38;5;241m1.15[39m [38;5;241m*[39m beam_width[38;5;241m*[39m[38;5;241m*[39mnum_tokens_to_generate, 
[1;32m      4[0m                                [38;5;28mmax[39m([38;5;241m5[39m, [38;5;241m2[39m [38;5;241m+[39m num_tokens_to_generate)), 
[1;32m      5[0m                       dpi[38;5;241m=[39m[38;5;241m300[39m)
[0;32m----> 7[0m pos [38;5;241m=[39m [43mnx[49m[38;5;241;43m.[39;49m[43mnx_agraph[49m[38;5;241;43m.[39;49m[43mgraphviz_layout[49m[43m([49m[43mgraph[49m[43m,[49m[43m [49m[43mprog[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mdot[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      8[0m scores [38;5;241m=[39m [data[[38;5;124m'[39m[38;5;124msequencescore[39m[38;5;124m'[39m] [38;5;28;01mfor[39;00m _, data [38;5;129;01min[39;00m graph[38;5;241m.[39mnodes(data[38;5;241m=[39m[38;5;28;01mTrue[39;00m)]
[1;32m     10[0m norm [38;5;241m=[39m Normalize(vmin[38;5;241m=[39m[38;5;28mmin[39m(scores), vmax[38;5;241m=[39m[38;5;28mmax[39m(scores))

File [0;32m~/anaconda3/envs/book_env/lib/python3.10/site-packages/networkx/drawing/nx_agraph.py:257[0m, in [0;36mgraphviz_layout[0;34m(G, prog, root, args)[0m
[1;32m    226[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mgraphviz_layout[39m(G, prog[38;5;241m=[39m[38;5;124m"[39m[38;5;124mneato[39m[38;5;124m"[39m, root[38;5;241m=[39m[38;5;28;01mNone[39;00m, args[38;5;241m=[39m[38;5;124m"[39m[38;5;124m"[39m):
[1;32m    227[0m [38;5;250m    [39m[38;5;124;03m"""Create node positions for G using Graphviz.[39;00m
[1;32m    228[0m 
[1;32m    229[0m [38;5;124;03m    Parameters[39;00m
[0;32m   (...)[0m
[1;32m    255[0m [38;5;124;03m    see https://gitlab.com/graphviz/graphviz/-/issues/1767 for more info.[39;00m
[1;32m    256[0m [38;5;124;03m    """[39;00m
[0;32m--> 257[0m     [38;5;28;01mreturn[39;00m [43mpygraphviz_layout[49m[43m([49m[43mG[49m[43m,[49m[43m [49m[43mprog[49m[38;5;241;43m=[39;49m[43mprog[49m[43m,[49m[43m [49m[43mroot[49m[38;5;241;43m=[39;49m[43mroot[49m[43m,[49m[43m [49m[43margs[49m[38;5;241;43m=[39;49m[43margs[49m[43m)[49m

File [0;32m~/anaconda3/envs/book_env/lib/python3.10/site-packages/networkx/drawing/nx_agraph.py:303[0m, in [0;36mpygraphviz_layout[0;34m(G, prog, root, args)[0m
[1;32m    301[0m     [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mpygraphviz[39;00m
[1;32m    302[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m [38;5;28;01mas[39;00m err:
[0;32m--> 303[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m([38;5;124m"[39m[38;5;124mrequires pygraphviz http://pygraphviz.github.io/[39m[38;5;124m"[39m) [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01merr[39;00m
[1;32m    304[0m [38;5;28;01mif[39;00m root [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    305[0m     args [38;5;241m+[39m[38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124m-Groot=[39m[38;5;132;01m{[39;00mroot[38;5;132;01m}[39;00m[38;5;124m"[39m

[0;31mImportError[0m: requires pygraphviz http://pygraphviz.github.io/

